@startuml device Config

partition "Extern system" {
    start
    :Send POST/PUT JSON;
}

partition "I-San Webserver" {
if (Save input data) then (error)
    stop
else (success)
endif
while (Check IP address PositionUnits)
    :check status of device;
endwhile (no more IP addresses (in data))

while (Check IP address LightingUnits)
    :check status of device;
endwhile (no more IP addresses (in data))

while (Check COM Port)
    :check status of camera/measurementUnit;


endwhile (no more com ports (in data))
if (posetive results available?) then (Yes)
    :Store results in Device_config/status;
    end

else (error)
    :Store error in Device_config/status;
end

@enduml
}




@startuml Scan config

partition "Extern system" {
    start
    :Send POST/PUT JSON;
}


partition "I-San Webserver" {
    if (Save input data) then (error)
    stop
else (success)
endif

:calculation resolution;

:calculation picturescope;

:save config in Scan_Config/Status;

end 
@enduml
}



@startuml Config Scan
start

:Überprüfe Bedingung;
if (Bedingung erfüllt?) then (Ja)
    :Aktion A;
else (Nein)
    :Aktion B;
endif

:Weiterer Schritt;
while (Wiederhole Bedingung?)
    :Aktion in Schleife;
endwhile (Fertig)

fork
    :Parallel 1;
fork again
    :Parallel 2;
end fork

stop
@enduml


@startuml Config COMPort
start

:Überprüfe Bedingung;
if (Bedingung erfüllt?) then (Ja)
    :Aktion A;
else (Nein)
    :Aktion B;
endif

:Weiterer Schritt;
while (Wiederhole Bedingung?)
    :Aktion in Schleife;
endwhile (Fertig)

fork
    :Parallel 1;
fork again
    :Parallel 2;
end fork

stop
@enduml




PUT/POST -> send : IP Adresses (max 3) from PositionUnits -> Ip Lightingmoduls (max X) -> schreiben in Json -> Verbindungstest mit ACK -> Antwort an PositionUnits ->